### ISSUE TITLE
problem about  mel2samp.py

### ISSUE THREAD

**Issue by UESTCgan** [NVIDIA/waveglow#7] opened 2018-11-09 09:59 UTC
It's a very nice work! I'm study it! But when I'm training the model, I find a problem. May, there is some mistake in mel2samp.py. It can't get a right mel.
When I use the "mel_spectrograms" that the NVIDIA gives, the results that "waveglow_old.pt" infers are nice. But ，when I use "python mel2samp.py -f test_files.txt -o . -c config.json"  to get mel,  the results that "waveglow_old.pt" infers are bad. The voice is from man, not the original woman.

the result of  "mel_spectrograms" that the NVIDIA gives:
![image](https://user-images.githubusercontent.com/40649244/48255585-27203300-e448-11e8-94a7-e1a0aefd84ce.png)

the result of  mel2samp.py
![image](https://user-images.githubusercontent.com/40649244/48255656-55057780-e448-11e8-92dc-4e6625920470.png)

This is my audio.
[my_results_wav.zip](https://github.com/NVIDIA/waveglow/files/2565391/my_results_wav.zip)

**Comment by UESTCgan** [comment] 2018-11-09 10:04
When I use "python mel2samp.py -f test_files.txt -o . -c config.json" to get mel, the high frequency part of the mel spectrum from result is also not good.

**Comment by azraelkuan** [comment] 2018-11-09 11:19
@UESTCgan because the model is trained on the LJSPEECH Dataset, you can genererate a good man voice from this model, Right?
u need to train your model using your data

**Comment by UESTCgan** [comment] 2018-11-09 11:53
I used the LJSPEECH Dataset and the model trained by NVIDIA. I just use "python mel2samp.py -f test_files.txt -o . -c config.json" to get mel.

**Comment by azraelkuan** [comment] 2018-11-09 12:51
@UESTCgan why u said "The voice is from man", the LJSpeech is female..., Do u mean that u use other mel_spectrograms from the LJSpeech and can't get good wav?

**Comment by UESTCgan** [comment] 2018-11-09 12:54
Yes! When I use other mel_spectrograms from the LJSpeech which are extract by mel2samp.py, I can't get good wav.The voice sound like a man voice.

**Comment by Arbaletos** [comment] 2018-11-09 13:19
It's because you must use external stft to get spectrogram. May be autors used different STFT to get their spectrograms, that does not match with yours.
Or maybe you have wrong stft parameters.

**Comment by azraelkuan** [comment] 2018-11-09 13:48
@Arbaletos i just change the dataset and sample rate

**Comment by rafaelvalle** [comment] 2018-11-09 21:20
It's probably due to a wrong mel_fmax value. We're confirming it.

**Comment by rafaelvalle** [comment] 2018-11-09 21:31
Pull the latest code from master, re-run the experiments and let us know.

**Comment by yhgon** [comment] 2018-11-09 22:21
I confirmed it works well in last commit..

**Comment by UESTCgan** [comment] 2018-11-10 00:43
@rafaelvalle Thanks for your reply! I will have a try!  Thanks again!

**Comment by UESTCgan** [comment] 2018-11-10 04:51
@rafaelvalle ，I have finished my test.The last commit is right! Thank you !
![image](https://user-images.githubusercontent.com/40649244/48297593-618cdd00-e4e7-11e8-919f-4cdde6148c46.png)

**Comment by rafaelvalle** [comment] 2018-11-10 04:58
Excellent. Closing the issue.

**Closed by rafaelvalle** 2018-11-10 04:58 UTC

**Comment by Hayes515** [comment] 2018-11-14 07:32
@UESTCgan  how can I get  mel_spectrograms  picture like this, using some software?

![default](https://user-images.githubusercontent.com/29434347/48466984-7688a980-e822-11e8-85c5-38402566caa1.png)

**Comment by UESTCgan** [comment] 2018-11-14 07:46
@Hayes515 Adobe Audition
